name: .NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: |
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: published-app
          path: ./publish

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Example deployment script
          # Replace the following lines with your actual deployment commands
          echo "Starting deployment..."
          # Example: Copy files to a remote server
          scp -r ./publish user@yourserver.com:/path/to/deploy
          echo "Deployment completed."

      - name: Clean up
        run: echo "Deployment finished."
